/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "Dio.h"  /* 修改：包含Dio模块头文件而不是ProductionCode.h */

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

/* 声明我们为Dio_ReadChannel编写的测试函数 */
extern void test_Os_MainTest(void);

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestMaclDio.c"); /* 修改：指向实际的测试文件名称 */
  
  /* 运行所有Dio_ReadChannel测试用例 */
  RUN_TEST(test_Os_MainTest, 20);
  
  /* 注意：行号(20, 30, 40等)是示例值，应调整为实际测试函数在TestMaclDio.c文件中的行号 */

  return (UnityEnd());
}
